version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
branches:
  only:
  - master
environment:
  WHEEL_DIR: C:\kivy_wheels
  COMPILER: mingw
  KIVY_BUILD_DIR: C:\kivy_build
  KIVY_BUILD_CACHE: C:\kivy_build_cache2
  AIRPLANE_CHARGE:
    secure: +uoVGbtMLNGC5M65CCkHpWJ2/M9KsAEPf8ncHWQ1We7sQaITsp3dpFCqi8bX38PvQPSCS+C3ZuVZIbaUXPxO1owibcv+1gxdATOUfVVF/JrTFwgauCH4LKy3jSJp0tYxL4FrOTEtUsHznmBjewHnkbKXx8cMMSLx9+FgQfUAjttjV3/mESNwbRVdFck2m4qSZfqVceRZKewjXsABO3JH0pQyWr9LdnWpJbSdVsp2a9uy4Q8QTUqWI5yj7QvPOQAT1HBNXm0xjOcnxQPZqa4DDtJWsHheVIlXWv+yvOUHb3kzZi8qXh7mGLowoia3Z6ZqWAYob3FWmFBMQg6RD+Z0M+VAnnaj3yvTicdroEAmnQE2XzRZV/saobjgzf2KENT7O8ymQwXc0Rz1NJAiLWvzYSZGQ61xJCclw+Ynk09AwdnrbmVaa/AHIQBp67CNsXcdt4VDz9pb7TzP2ZwwYVzTPOLP1NEpYxZJOXroaKPnlOnWoKNCjTQ05uFlPjufHSPGtZcDtub22A4+i9yHrxg52wfdmk+g9PB7Oykq4eali2HKb8eJwsHp95GXNFcU/MAxg7PIRfwNzMmt/iR4UOy9dPmBGDA+bwUaiBTg8GsxrybjzK9bfGrdKvaXmHHKOaBaN11RZ1qKlBXjZ6HS93Qiry3aWOrNF3ML9St7rit1/Kccd46RI57X2e2YoAsJdQ/3l9e4rlX2rHsnCsNifKzn+7p+5qDGPWxWEDdQpANzxzQ2Q98SnW5xfzYPJgxmoBpndM0PasgJoYtc/Y5s8z2b7NE+QKhckN4QRb42zOgh1jPnLydXBQkXKJU60YI2ZOwjT1JTxrh/2nlzoYFUnKUMcRkFIMb73234Vbj+r7f1cBm/csbzseoSLbmLwAn1dBMeQUHLpzJ8dO5C+Be9s0rfqxAt77jw0zX4PeiTtbEuMM7OwENeBlv6igvEh1/7CrLl0e8d6K8D1samG3MXT3dFMwLXiIjupU8qoJjlMWEDkXXAxWMG/WQ0mdI6wio1XveCsKZJlmSSbTC3dstsRV0FvHL0jSr0HKNtv/MqwTOVmGyYNJSWw1GJh7wtiVRmZzRqoL1zKQMhyibot/w3i6r0k3bg9xW1J0Y9SdJrE5zRNYBTBbRHd+PE2UZjY0KKT5RInUKK+UtFfaAIrChGM8bYSobfdjr1eC+vPW4ToKiUCtCB6av4pw90sgUVUNe3IS0WTttYR1wzlG1TCaZ2V1dh77A/xnuZ1rHqEvkdhCHz9fgOs81Pxcttzwdgcab6a5DC1zKKWSN1LpoginjRqtZy1A==
  GDRIVE_CLIENT_ID:
    secure: YveQ/6qU0u9IxPifp/1nn3EXB5exgSMJjPCgrFeiGCL0F8eCEZCCFYnJR7B5Mu7DC3HP28vuozky4y8z/qlifUCRL0un/3+9H2AcSnPMs1A=
  GDRIVE_CLIENT_SECRET:
    secure: jQVAqlWZq5IL/kchbABd7vYZ1JCz9Yq7uozFxFGtjC8=
  GDRIVE_sdl2_UPLOAD_ID: 0B1_HB9J8mZepTVJhenRET01VQTQ
  GDRIVE_sdl2_dev_UPLOAD_ID: 0B1_HB9J8mZepWlZMNWVKVHE5R28
  GDRIVE_glew_UPLOAD_ID: 0B1_HB9J8mZepUkJ3TTJhY0ZuWGs
  GDRIVE_glew_dev_UPLOAD_ID: 0B1_HB9J8mZepak1KeGJ5MDdSQ0E
  GDRIVE_gstreamer_UPLOAD_ID: 0B1_HB9J8mZepNzZ5aW91Q0tJU2s
  GDRIVE_gstreamer_dev_UPLOAD_ID: 0B1_HB9J8mZepZzNSZVI2V19mQ00
  GDRIVE_angle_UPLOAD_ID: 0B1_HB9J8mZepRDltSDB6Z0FVT00
  GDRIVE_angle_dev_UPLOAD_ID: fake
  matrix:
  - PACKAGE_TARGET: sdl2
    PYVER: 27
    BITTNESS: 86
  - PACKAGE_TARGET: glew
    PYVER: 27
    BITTNESS: 86
  - PACKAGE_TARGET: gstreamer
    PYVER: 27
    BITTNESS: 86
  - PACKAGE_TARGET: angle
    PYVER: 27
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: sdl2
    PYVER: 33
    BITTNESS: 86
  - PACKAGE_TARGET: glew
    PYVER: 33
    BITTNESS: 86
  - PACKAGE_TARGET: gstreamer
    PYVER: 33
    BITTNESS: 86
  - PACKAGE_TARGET: angle
    PYVER: 33
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: sdl2
    PYVER: 34
    BITTNESS: 86
  - PACKAGE_TARGET: glew
    PYVER: 34
    BITTNESS: 86
  - PACKAGE_TARGET: gstreamer
    PYVER: 34
    BITTNESS: 86
  - PACKAGE_TARGET: angle
    PYVER: 34
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: sdl2
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 35
    BITTNESS: 86
    COMPILER: msvc
  - PACKAGE_TARGET: sdl2
    PYVER: 27
    BITTNESS: 64
  - PACKAGE_TARGET: glew
    PYVER: 27
    BITTNESS: 64
  - PACKAGE_TARGET: gstreamer
    PYVER: 27
    BITTNESS: 64
  - PACKAGE_TARGET: angle
    PYVER: 27
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: sdl2
    PYVER: 33
    BITTNESS: 64
  - PACKAGE_TARGET: glew
    PYVER: 33
    BITTNESS: 64
  - PACKAGE_TARGET: gstreamer
    PYVER: 33
    BITTNESS: 64
  - PACKAGE_TARGET: angle
    PYVER: 33
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: sdl2
    PYVER: 34
    BITTNESS: 64
  - PACKAGE_TARGET: glew
    PYVER: 34
    BITTNESS: 64
  - PACKAGE_TARGET: gstreamer
    PYVER: 34
    BITTNESS: 64
  - PACKAGE_TARGET: angle
    PYVER: 34
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: sdl2
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: glew
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: gstreamer
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
  - PACKAGE_TARGET: angle
    PYVER: 35
    BITTNESS: 64
    COMPILER: msvc
cache: C:\kivy_build_cache2
build_script:
- ps: >-
    function Check-Error
    {
      param([int]$SuccessVal = 0)
      if ($SuccessVal -ne $LastExitCode) {
        throw "Failed with exit code $LastExitCode"
      }
    }


    $env:SSL_CERT_FILE="C:\projects\kivy-sdk-packager\win\DST Root CA X3.pem"

    cd C:\projects\kivy-sdk-packager


    mkdir "$env:KIVY_BUILD_DIR"

    mkdir "$env:WHEEL_DIR"

    if (!(Test-Path "$env:KIVY_BUILD_CACHE")) {
      mkdir "$env:KIVY_BUILD_CACHE"
    }

    $GDRIVE_ID = [Environment]::GetEnvironmentVariable("GDRIVE_$env:PACKAGE_TARGET`_UPLOAD_ID", "Process")

    $DEV_GDRIVE_ID = [Environment]::GetEnvironmentVariable("GDRIVE_$env:PACKAGE_TARGET`_dev_UPLOAD_ID", "Process")



    if ($env:BITTNESS -eq "64") {
      $PYTHON_ROOT = "C:\Python$env:PYVER-x64"
      $WHELL_BITNESS = "win_amd64"
    } else {
      $PYTHON_ROOT = "C:\Python$env:PYVER"
      $WHELL_BITNESS = "win32"
    }

    $env:PATH = "$PYTHON_ROOT;$PYTHON_ROOT\Scripts;$env:PATH"



    $WHEEL_VERSION = python -c "import win.$env:PACKAGE_TARGET;print(win.$env:PACKAGE_TARGET.__version__)"

    Check-Error

    $WHEEL_BIN = "kivy.deps.$env:PACKAGE_TARGET-$WHEEL_VERSION-cp$env:PYVER-cp$env:PYVER`m-$WHELL_BITNESS.whl"

    $WHEEL_DEV = "kivy.deps.$env:PACKAGE_TARGET`_dev-$WHEEL_VERSION-cp$env:PYVER-cp$env:PYVER`m-$WHELL_BITNESS.whl"


    C:\Python27\Scripts\pip.exe install pydrive

    Check-Error

    $ALREADY_EXISTS = C:\Python27\python.exe win\gdrive.py exists "$GDRIVE_ID" "$WHEEL_BIN"

    Check-Error

    if ($ALREADY_EXISTS -eq "True" -and $DEV_GDRIVE_ID -ne "fake") {
      $ALREADY_EXISTS = C:\Python27\python.exe win\gdrive.py exists "$DEV_GDRIVE_ID" "$WHEEL_DEV"
      Check-Error
    }

    echo "Already exists=$ALREADY_EXISTS $WHEEL_BIN $WHEEL_DEV"


    if ($ALREADY_EXISTS -eq "False") {
      python -m pip install pip wheel setuptools --upgrade
      Check-Error
      if ($env:COMPILER -eq "mingw") {
        pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy
        Check-Error
      }

      echo "Executing win.$env:PACKAGE_TARGET build_path $env:KIVY_BUILD_DIR arch $env:BITTNESS pyver $env:PYVER package $env:PACKAGE_TARGET output $env:WHEEL_DIR cache $env:KIVY_BUILD_CACHE compiler $env:COMPILER"
      python -m win.$env:PACKAGE_TARGET build_path "$env:KIVY_BUILD_DIR" arch $env:BITTNESS pyver $env:PYVER package $env:PACKAGE_TARGET output "$env:WHEEL_DIR" cache "$env:KIVY_BUILD_CACHE" compiler "$env:COMPILER"
      Check-Error

      if ($DEV_GDRIVE_ID -ne "fake") {
        C:\Python27\python.exe win\gdrive.py upload "$DEV_GDRIVE_ID" "$env:WHEEL_DIR\kivy.deps.$env:PACKAGE_TARGET`_dev*"
        Check-Error
      }
      C:\Python27\python.exe win\gdrive.py upload "$GDRIVE_ID" "$env:WHEEL_DIR\kivy.deps.$env:PACKAGE_TARGET-*"
      Check-Error
    }
