<ItemsDetailTableButton>:
    id: items_detail_table_button
    markup: True
    font_size:sp(15)
    markup: True
    disabled: False
    text_size: self.size
    size_hint: 1, 1
    valign: 'middle'
    halign: 'center'

<ItemsDetailTableRV@RecycleView>:
    viewclass: 'ItemsDetailTableButton'
    SelectableRecycleGridLayout:
        bar_width: dp(5)
        size_hint_y:None
        size_hint_x:1
        height: self.minimum_height
        spacing: 1
        cols:4