<ItemsDetailTableButton>:
    id: items_detail_table_button
    markup: True
    font_size:sp(15)
    disabled: False
    text_size: self.size
    valign: 'middle'
    halign: 'center'
    spacing: 0

<ItemsDetailTableRV@RecycleView>:
    viewclass: 'ItemsDetailTableButton'
    SelectableRecycleGridLayout:
        bar_width: dp(5)
        default_size: None, dp(50)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        spacing: 1
        cols:4